### ISSUE TITLE
Simulation cutoffs

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/pystablemotifs#28]
Right now, the code asks for a single size cutoff for the STG. There are few problems here:

1. The cutoff is called max_simulate_size, and refers to the number of variables, not states. Is this confusing?

2. The same cutoff is used for i) the full system, ii) the rspace system, iii) the VC-reduced system. Is there a situation in which we might want these to be different?

3. There is no option to pick a system (reduced, rspace, etc.) to simulate based on their relative sizes. Is that an important feature to add?

It's important to remember that doing the VC reduction is not free, so if the rspace is small, it is much faster to just simulate that then it is to calculate the VC reduction, even if the VC reduction ends up being smaller than the rspace system.

**Comment by jcrozum** [comment]
Related to this:

Should we precompute a network deletion reduction as a "starting point" for further deletion reduction. If so, under what conditions?

I think this could potentially give some pretty major speed-up in systems that require multiple deletion reductions.

**Comment by jcrozum** [comment]
One other addition: we should allow the user to set the max_in_degeree parameter for the deletion projection that is used in the main succession diagram algorithm.

**Comment by jcrozum** [comment]
The lack of a max_in_degree parameter for the deletion reduction came in a discussion in issue #72, so I think we should prioritize implementing that.

**Comment by troonmel** [comment]
max_in_degree parameter is added in simulation_cutoff branch

**Comment by troonmel** [comment]
max_simulation_size_vc was added in simulation_cutoff branch

**Comment by jcrozum** [comment]
As of #79, the desired features mentioned in this thread are in the main branch, so I'm closing this issue.

In future, we may consider using a "starting point" deletion reduction to help speed things up, but this idea will require additional theory work before we can implement it, so we'll save that task for another day.
