### ISSUE TITLE
error using AttractorRepertoire 

### ISSUE THREAD

**Issue by alekhyaa2** [jcrozum/pystablemotifs#74]
I am using the below command to print the attractors for my system. 
ar=sm.AttractorRepertoire.from_primes(primes,max_simulate_size=5)

I am getting the following error. 

ERROR: trap_spaces is removed, use compute_trap_spaces
An exception has occurred, use %tb to see the full traceback.
SystemExit: 1

Could please help me understand what this error is about?

**Comment by jcrozum** [comment]
This problem stems from a version mismatch between pystablemotifs and pyboolnet; please make sure you are using the most recent version of both of these.

**Comment by alekhyaa2** [comment]
I am using pyboolnet - version 3.0.9 and pystablemotifs 3.0.2.

**Comment by jcrozum** [comment]
I see; the latest release is actually 3.0.3. I created a new release on GitHub, and will update PyPI tomorrow. For now, you can run this to update:
```
pip uninstall pystablemotifs
pip install git+https://github.com/jcrozum/pystablemotifs
```

**Comment by alekhyaa2** [comment]
It works now after getting the latest version of Pystablemotifs. Thank you for your quick help!

**Comment by jcrozum** [comment]
Glad to help! The PyPI version should also be 3.0.3 now.
