### ISSUE TITLE
MPBN

### ISSUE THREAD

**Issue by yzongy** [jcrozum/pystablemotifs#75]
Hi Jordan,

Another task for me is to detect actractors on a genome-scale network:
[processed_BottomStrain_GRNbased.txt](https://github.com/jcrozum/pystablemotifs/files/8284315/processed_BottomStrain_GRNbased.txt)

So that I set the MPBN_update parameter as True, which I assume is a quick solution for searching attractors.
```
print("finding attractors")
max_simulate_size=7
ar = sm.AttractorRepertoire.from_primes(primes, max_simulate_size=max_simulate_size,max_stable_motifs=10000,MPBN_update=True)
```

But in fact, it did not finish overnight on my Mac though it is said that MPBN is designed for genome-scale networks.

Just wondering if I missed something?

Best,

Bill

**Comment by yzongy** [comment]
Yes Jordan! `pyboolnet.compute_trap_spaces(primes,"min")` is what I was looking for. 
As you said in #76, `pyboolnet.compute_trap_spaces(primes,"min")` will pair well with a pystablemotifs function that can find controlling strategies with a given attractor but without calculating all possible attractors. 
This will be a good solution to figure out approaches to drive large scale Boolean networks.
Thanks again!

**Comment by yzongy** [comment]
Just being curious, though my question has been solved, is there a way to estimate how much time will it take to find attractors with a given large network like the one in this post? Or do we know if it is possible to complete the following script within a reasonable time?
`sm.AttractorRepertoire.from_primes(primes,max_simulate_size=max_simulate_size,max_stable_motifs=10000,MPBN_update=True)`

**Comment by jcrozum** [comment]
Sorry for the slow response. I don't know of any way to estimate the time it will take a priori, but in general, the time scales with number of nodes, number of edges, and number of positive feedback loops in the network.

**Comment by jcrozum** [comment]
This issue seems to be resolved for the time being, so I'm closing it to keep things tidy. Feel free to open a new issue if there's more that needs to be discussed on this topic.
