### ISSUE TITLE
Integration in the CoLoMoDo Docker

### ISSUE THREAD

**Issue by pauleve** [jcrozum/pystablemotifs#78]
Hello,
Currently, the (deprecated) java implementation of StableMotifs is shipped in the [CoLoMoTo Docker distribution](https://github.com/colomoto/colomoto-docker), and I'd like to upgrade it to this new one.
This requires two tasks:
- [x] conda packaging: this should be quite straightforward, based on your PyPi one, especially as PyBoolNet as a conda package as well. I was thinking at doing it in the https://github.com/colomoto/colomoto-conda, unless you have other preferences. The downside is that on upgrade, you should notifiy me or make pull request there to upgrade the conda package as well. The alternative is that you handle the conda package publishing on your side (in a dedicated conda channel)
- [x] supply one or two demonstration notebooks (that are also used to validate the docker image by checking one can run them without error). Looking at your example folder, https://github.com/jcrozum/pystablemotifs/blob/master/Examples%20and%20Tutorials/Basic%20Usage%20Tutorial.ipynb sounds a good candidate "as is", and maybe the first part of https://github.com/jcrozum/pystablemotifs/blob/master/Examples%20and%20Tutorials/Control%20Tutorial.ipynb, where the model could also be imported from ginsim or SBML-qual so user can easily see how to import their own ones. Unless alternative notebooks would be a better choice?

I can do most of this work soon, but I'd like to have your approval and ideas first.

**Comment by jcrozum** [comment]
Hi Loïc! You certainly have our approval to go ahead with this. Doing the conda packaging in colomoto-conda is fine with us. Feel free to repurpose/modify any of the notebooks. The two you identified are good choices for demonstrations.

Please let us know what you need from us.

**Comment by pauleve** [comment]
Alright, so it looks like the next release of colomoto-docker will include pystablemotifs :-)
Here are the notebooks I put for demonstration:
https://nbviewer.org/github/colomoto/colomoto-docker/tree/for-next/tutorials/pystablemotifs/
For the control tutorial, I added a small section showing how to import an arbitrary model

**Comment by jcrozum** [comment]
Sorry for the slow response. I looked over the notebook demonstrations, and they look good to me. Everything seems to be all set, so I'll close this issue. Thanks for adding pystablemotifs to the CoLoMoTo docker!
