### ISSUE TITLE
Initial state of nodes in a network

### ISSUE THREAD

**Issue by priyambial123** [jcrozum/pystablemotifs#82]
Is the number of source nodes determines the number of attractors?. For example, I have three source nodes in the network (13 nodes) and I have 2 ^ 3 = 8 attractors. In the state transition graph (STG), I could only see the state of the source nodes and state of other nodes are not shown. Is this because of the large number of nodes and hard to create a STG  with initial state of all nodes?

Thanks
Priya
![Figure_1_cluster1_prenatal](https://user-images.githubusercontent.com/11889537/175308462-cd9b8c4b-4f57-4527-8592-5167b7caa0d2.png)

**Comment by jcrozum** [comment]
It seems to be working, but your code does not display the plots or save the STGs. The code below worked for me:

```python
import pystablemotifs as sm
import pyboolnet
import pystablemotifs.export as ex
import networkx as nx
import matplotlib.pyplot as plt
rules='''DCAF5*= not (miR335 or miR124 or miR4507 or miR653 or miR3154 or miR5191 or X1) and (BCL6 or MYC or KDM5A or KDM2B or TCF4)
BCL6*= not (miR124 or miR335)
MYC*= not (miR335)
KDM5A*= not (miR335)
KDM2B*= KDM2B
TCF4*= TCF4
miR335*= BCL6 or MYC or KDM5A
miR4507*= BCL6 or TCF4
miR653*= MYC or KDM5A
miR3154*= MYC
miR5191*= MYC or KDM5A or TCF4
X1*= KDM2B
miR124*= miR124'''

primes = sm.format.create_primes(rules)

max_simulate_size=20
ar=sm.AttractorRepertoire.from_primes(primes, max_simulate_size=max_simulate_size)
ar.summary()

df=ex.attractor_dataframe(ar)
df

for a in ar.attractors:
    if a.n_unfixed == 0: continue # skip steady states
    print(a.attractor_dict)
    nx.draw(a.stg,with_labels=True)
    plt.show()
```

This is the same as the code you posted, but I've added `import matplotlib.pyplot as plt` to the top and `plt.show()` to the for loop. You might also want to consider saving the graphs to files using the [exporting tools in networkx](https://networkx.org/documentation/stable/reference/readwrite/index.html).

It should be noted that the STGs being plotted are subgraphs of the full STG. Specifically, these are the terminal strongly connected components (i.e., attractors) of the full STG.

**Comment by priyambial123** [comment]
Thank you, it worked
