### ISSUE TITLE
Update of node state in the network

### ISSUE THREAD

**Issue by priyambial123** [jcrozum/pystablemotifs#84]
Hello

How are the node states updated in the network. Is it asynchronous update? I ran the attractor analysis and in the figure, it shows that source nodes determine the next state of the nodes. When we assume it an asynchronous update of nodes, state of the nodes are randomly updated. Are the source node states randomly updated here? Can you explain how the nodes are updated in the attractor analysis

Thanks
![Figure_1_cluster1_prenatal](https://user-images.githubusercontent.com/11889537/177534004-abd36148-220b-4dac-9a24-2671900d0c40.png)

Priya

**Comment by jcrozum** [comment]
By default, pystablemotifs assumes asynchronous update, in which a single node is randomly chosen to be updated at each time step. Updating a source node (like A*=A) will not change its value.

We also consider all possible initial conditions, which is reflected in the different source node values you see in the figure; they correspond to different initial conditions.

**Comment by jcrozum** [comment]
I'm marking this as closed because simulation is currently not within the project scope for pystablemotifs.
